import '@testing-library/jest-dom/vitest'

// Mock HTMLCanvasElement for ECharts compatibility in jsdom
HTMLCanvasElement.prototype.getContext = function () {
  return {
    clearRect: () => {},
    getImageData: () => ({ data: [] }),
    fillRect: () => {},
    fillText: () => {},
    measureText: () => ({ width: 0 }),
    createLinearGradient: () => ({ addColorStop: () => {} }),
    createRadialGradient: () => ({ addColorStop: () => {} }),
    save: () => {},
    restore: () => {},
    translate: () => {},
    rotate: () => {},
    scale: () => {},
    setTransform: () => {},
    beginPath: () => {},
    closePath: () => {},
    moveTo: () => {},
    lineTo: () => {},
    rect: () => {},
    arc: () => {},
    stroke: () => {},
    fill: () => {},
    clip: () => {},
    strokeRect: () => {},
    strokeText: () => {},
    drawImage: () => {},
    createPattern: () => ({}),
    putImageData: () => {},
    globalAlpha: 1,
    globalCompositeOperation: 'source-over',
    fillStyle: '#000',
    strokeStyle: '#000',
    lineWidth: 1,
    lineCap: 'butt',
    lineJoin: 'miter',
    font: '',
    textAlign: 'start',
    textBaseline: 'alphabetic',
    canvas: {} as HTMLCanvasElement,
  } as CanvasRenderingContext2D
} as unknown as typeof HTMLCanvasElement.prototype.getContext
